name: Build and deploy

on:
  push:
    tags:        
      - 'v*'   
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Build project  
      run: |
        npm install
        npm run generate

    # NOTE: this fails when there isn't an empty .ftp-deploy-sync-state.json (or state-name attribute) on the server, see: https://github.com/SamKirkland/FTP-Deploy-Action/issues/153
    - name: FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./.output/public/

        
        
            
    
